[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dework_program = "92sorgqaDHqG5T12ZqrTMSCFZEHaVxrANLWdSQ5fFUom"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
